language: php

sudo: false
 
notifications:
  email: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

dist: precise

branches:
  only:
    - master

script: 
  - phpunit -c phpunit.xml --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
