language: php

sudo: false

notifications:
  email: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0.27
  - 7.1
  - 7.2

dist: precise

branches:
  only:
    - master

before_script:
  - bash tests/bin/travis.sh before

script:
  - phpunit -c phpunit.xml --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
